# Generated by Django 3.2.4 on 2021-06-17 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frssapi', '0002_alter_answers_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='option_id',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='question_id',
            new_name='question',
        ),
        migrations.AddField(
            model_name='options',
            name='point_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('question', 'user')},
        ),
    ]
